name: Update direct requirements

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install pipreqs
        run: pip install pipreqs

      - name: Regenerate requirements.txt with direct imports
        run: |
          pipreqs . --force --encoding=utf-8

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: regenerate requirements.txt (direct packages only)"
          branch: auto/update-direct-requirements
          title: "Update requirements.txt (direct packages only)"
          body: |
            This PR regenerates `requirements.txt` using pipreqs to include only directly used packages.
          delete-branch: true
